{{- if and .Values.groq.createSecret .Values.groq.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.groq.apiKeySecret }}
type: Opaque
stringData:
  GROQ_API_KEY: {{ .Values.groq.apiKey | quote }}

{{- end }}
